### ISSUE TITLE
search by city:Bucuresti should return same data as searching by city:București

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/solr#27]
search by city:Bucuresti should return same data as searching by city:București

**Comment by CalinCatuta** [comment]
https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-FuzzySearches

Documentatie despre cum functioneaza FuzzySearches.
Problem a fost rezolvata fara a fi nevoie de schimbare in SOLR, datele de genul city se trimit cu exemplu : Bucuresti~ 
Daca pui un numar dupa  atunci poti sa-i spui cate caractere pot sa difere in cuvant.
In mod normal n-ar trebui sa fie nevoie sa cauti cu fuzzy nume de orasear trebui sa fie intr-un singur fel in baza de date, ca sa poti sa faci Facets in solr.
Facets iti returneaza toate valorile unice, de la ce field-uri vrei tu, in functie de ce ai cautat, ca sa poti sa faci filtrari dinamice.

**Comment by sebiboga** [comment]
nice

**Comment by CalinCatuta** [comment]
Nu.
